name: _draft_release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release_drafter:
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
