name: _release

on:
  workflow_dispatch:
  release:
    types:
      - published
      
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Bump floating tag
        env:
          FLOATING_TAG: v1
        run: |
          git fetch --tags -f
          git tag ${{ env.FLOATING_TAG }} -f
          git push --tags -f     
